-- $BEGIN
INSERT INTO mamba_fact_art_follow_up (client_id,
                                      weight_in_kg,
                                      cd4_count,
                                      current_who_hiv_stage,
                                      nutritional_status,
                                      tb_screening_result,
                                      enrollment_date,
                                      hiv_confirmed_date,
                                      art_start_date,
                                      days_difference,
                                      followup_date,
                                      regimen,
                                      arv_dose_days,
                                      pregnancy_status,
                                      breast_feeding_status,
                                      follow_up_status,
                                      ti,
                                      treatment_end_date,
                                      next_visit_date,
                                      latest_followup_date,
                                      latest_followup_status,
                                      latest_regimen,
                                      latest_arv_dose_days,
                                      hiv_viral_load_count,
                                      hiv_viral_load_status,
                                      viral_load_test_status,
                                      on_antiretroviral_therapy,
                                      viral_load_test_indication,
                                      antiretroviral_side_effects,
                                      anitiretroviral_adherence_level,
                                      date_of_reported_hiv_viral_load,
                                      date_viral_load_results_received,
                                      routine_viral_load_test_indication,
                                      targeted_viral_load_test_indication)
                                          SELECT
                                          client_id,
                                      weight_in_kg,
                                      cd4_count,
                                      current_who_hiv_stage,
                                      nutritional_status,
                                      tb_screening_result,
                                      enrollment_date,
                                      hiv_confirmed_date,
                                      art_start_date,
                                      days_difference,
                                      followup_date,
                                      regimen,
                                      arv_dose_days,
                                      pregnancy_status,
                                      breast_feeding_status,
                                      follow_up_status,
                                      ti,
                                      treatment_end_date,
                                      next_visit_date,
                                      latest_followup_date,
                                      latest_followup_status,
                                      latest_regimen,
                                      latest_arv_dose_days,
                                      hiv_viral_load_count,
                                      hiv_viral_load_status,
                                      viral_load_test_status,
                                      on_antiretroviral_therapy,
                                      viral_load_test_indication,
                                      antiretroviral_side_effects,
                                      anitiretroviral_adherence_level,
                                      date_of_reported_hiv_viral_load,
                                      date_viral_load_results_received,
                                      routine_viral_load_test_indication,
                                      targeted_viral_load_test_indication
      FROM mamba_flat_encounter_follow_up
               JOIN mamba_flat_encounter_follow_up_1 enc_follow_up_1
                    on enc_follow_up_1.encounter_id = mamba_flat_encounter_follow_up.encounter_id
               LEFT JOIN mamba_flat_encounter_intake_a int_a on subquery.client_id = int_a.client_id
      where art_antiretroviral_start_date is not null

-- $END
